apiVersion: v1
kind: Service
metadata:
  name: issuance-service-web
  namespace: dgca-test
  labels:
    app: issuance-service-web
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: issuance-service-web
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuance-service-web
  namespace: dgca-test
  labels:
    app: issuance-service-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuance-service-web
  template:
    metadata:
      labels:
        app: issuance-service-web
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: issuance-service-web
          image: docker.pkg.github.com/courobin/dgca-issuance-web/dgca-issuance-web:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dgca-issuance-web
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          readinessProbe:
            httpGet:
              path: /
              port: 80

